### ISSUE TITLE
Provision AWS infrastructure

### ISSUE THREAD

**Issue by jonleeyz** [jonleeyz/bball8bot#9]
- [x] Configure AWS provider: #14
- [x] Create SQS module
- [ ] Create API Gateway module
- [x] Create Lambda module: #15 
- [x] Provision SQS module
- [ ] Provision API Gateway module
- [x] Provision Lambda module: #16, #17 
- [ ] Test functionality of Lambda module
- [ ] Test functionality of API Gateway module
- [ ] Test functionality of SQS module
- [ ] Test integration between API Gateway -> SQS modules
- [ ] Test integration between SQS -> Lambda modules

**Comment by jonleeyz** [comment]
Decomposed into #15, #19, #20, #21, #22, #23, #24, #25, #26, #27, #28, #29.
